#!/usr/bin/env bash

#: exec_target = cli

## Run Code Sniffer (phpcbf) against given path
##
## Usage: fin kit/phpcbf <path>
##
## Uses Drupal standards.
##
## Includes extensions: php, module, inc, install, test, profile, theme
## Ignores:   *.pages*.inc

set -e

#-------------------------- Execution --------------------------------
phpcbf \
  --standard=Wordpress-Core -n \
  --extensions="php" \
  "$@"
#-------------------------- END: Execution --------------------------------
