#!/usr/bin/env bash

#: exec_target = cli

## Run Code Sniffer (phpcs) against given path
##
## Usage: fin kit/phpcs <path>
##
## Uses Drupal standards.
##
## Includes extensions:	php, module, inc, install, test, profile, theme
## Ignores:		features.*, *.pages*.inc

set -e

#-------------------------- Execution --------------------------------
# Wrap the command below to hide output.
phpcs \
  --standard=Wordpress-Core -n \
  --extensions="php" \
  "$@"
#-------------------------- END: Execution --------------------------------
