name: Test and Lint Artifact
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    name: Build Project
    env:
      RUN_AS_CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Docksal
        run: curl -fsSL https://get.docksal.io | bash
      - name: Start Docksal
        run: fin start
      - name: Build Project
        run: fin ci-init
      - name: Create Artifact
        run: tar --exclude='wp-content/uploads' -czvf deploy-artifact.tar.gz -C docroot/ wp-content/
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy-artifact
          path: deploy-artifact.tar.gz
  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: build
    env:
      FLYWHEEL_ID: jcourtice
      FLYWHEEL_REMOTE_SITE: ci-cd-test-site
    steps:
      - name: Download deploy artifact
        uses: actions/download-artifact@v2
        with:
          name: deploy-artifact
          path: ${{ runner.temp }}
      - name: Unzip Deploy Artifact into workspace
        run: tar -xf ${{ runner.temp }}/deploy-artifact.tar.gz -C ${{ github.workspace }}
      - name: Deploy files to remote site
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BS2WP_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.FLYWHEEL_HOST }}
          REMOTE_USER: ${{ secrets.FLYWHEEL_SSH_USER }}
          ARGS: -rltgoDzvO
          TARGET: /www

